spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studio_medico
    username: root
    password: C1s9a2c8c3m7s?
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
