spring:
  datasource:
<<<<<<< HEAD
    url:  jdbc:mysql://localhost:3306/studiomedico
    username: admin
    password: Patrick1997
    driver-class-name:  com.mysql.cj.jdbc.Driver
=======
    url: jdbc:mysql://localhost:3306/studio_medico
    username: root
    password: C1s9a2c8c3m7s?
    driver-class-name: com.mysql.cj.jdbc.Driver
>>>>>>> 8fb867e502fe4b9bfe59737a06370dc0f20df82c
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
